# Copyright (c) 2020-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the license found in the LICENSE file in
# the root directory of this source tree.
#

from typing import AnyStr, Optional

class DBusBaseError(Exception):
    errno: int
    def __init__(
        self,
        errno: int,
        err_name: Optional[AnyStr] = None,
        err_message: Optional[AnyStr] = None,
    ) -> None: ...

class DBusFailedError(DBusBaseError): ...
class DBusNoMemoryError(DBusBaseError): ...
class DBusServiceUnknownError(DBusBaseError): ...
class DBusNameHasNoOwnerError(DBusBaseError): ...
class DBusNoReplyError(DBusBaseError): ...
class DBusIOErrorError(DBusBaseError): ...
class DBusBadAddressError(DBusBaseError): ...
class DBusNotSupportedError(DBusBaseError): ...
class DBusLimitsExceededError(DBusBaseError): ...
class DBusAccessDeniedError(DBusBaseError): ...
class DBusAuthFailedError(DBusBaseError): ...
class DBusNoServerError(DBusBaseError): ...
class DBusTimeoutError(DBusBaseError): ...
class DBusTimedOutError(DBusBaseError): ...
class DBusNoNetworkError(DBusBaseError): ...
class DBusAddressInUseError(DBusBaseError): ...
class DBusDisconnectedError(DBusBaseError): ...
class DBusInvalidArgsError(DBusBaseError): ...
class DBusFileNotFoundError(DBusBaseError): ...
class DBusFileExistsError(DBusBaseError): ...
class DBusUnknownMethodError(DBusBaseError): ...
class DBusUnknownObjectError(DBusBaseError): ...
class DBusUnknownInterfaceError(DBusBaseError): ...
class DBusUnknownPropertyError(DBusBaseError): ...
class DBusPropertyReadOnlyError(DBusBaseError): ...
class DBusUnixProcessIdUnknownError(DBusBaseError): ...
class DBusInvalidSignatureError(DBusBaseError): ...
class DBusInconsistentMessageError(DBusBaseError): ...
class DBusMatchRuleNotFoundError(DBusBaseError): ...
class DBusMatchRuleInvalidError(DBusBaseError): ...
class DBusInteractiveAuthorizationRequiredError(DBusBaseError): ...
class DBusNoSuchUnitError(DBusBaseError): ...
class DBusConnectionRefusedError(DBusBaseError): ...
class DBusInterruptedError(DBusBaseError, InterruptedError): ...
